# Deploy a cloudbeat instance per node for cis policy
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cloudbeat
  namespace: kube-system
  labels:
    k8s-app: cloudbeat
spec:
  template:
    spec:
      containers:
        - name: cloudbeat
          env:
            - name: CLOUDBEAT_TYPE
              value: cloudbeat/eks
