name: Cloudbeat-CI

on:
  pull_request:
    branches:
      - main

env:
  K8S_MANIFEST_DIR: deploy/k8s
  GO_VERSION: 1.17.2

jobs:
  integration-test:
    name: Integration Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Configure sysctl limits
        run: |
          echo ${{ secrets.FORK_TEST }}