name: Deploy Environment Action

on: 
  push:
    branches:
      - "ci-actions-testing-V2"
env:
  K8S_MANIFEST_DIR: deploy/k8s
  GO_VERSION: 1.17.2

# steps:
# 1. Checkout repo
# 2. Setup kind
# 3. Deploy ES on kind with helm
# 4. Deploy cloudbeat
# 5. Build & deploy test docker
# 6. Save artifacts 
# 7. Show artifacts(gh pages/bucket)
jobs:
  pytest-integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        with:
          config: deploy/k8s/kind/kind-config.yaml
          cluster_name: kind-mono 

      - name: Docker build Cloudbeat
        run: |
          GOOS=linux go build -v && docker build -t cloudbeat . && kind load docker-image cloudbeat:latest --name kind-mono
      
      - name: Docker build tests-container
        run: |
          cd tests; docker build -t cloudbeat-test:0.0.6 . && kind load docker-image cloudbeat-test:0.0.6 --name kind-mono
      
      - uses: azure/setup-helm@v1
        id: install
      
      - name: Deploy tests Helm chart
        run: |
          helm upgrade --wait --install --values tests/deploy/k8s-cloudbeat-tests/k8s-values.yaml --namespace kube-system --kube-context kind-kind-mono cloudbeat-tests  tests/deploy/k8s-cloudbeat-tests/ 

      - name: Sleep for 10s
        uses: juliangruber/sleep-action@v1
        with:
          time: 100s
      - name: run tests
        run: |
          helm test cloudbeat-tests --namespace kube-system --kube-context kind-kind-mono --logs