name: Deploy Environment Action
on: push
jobs:
  elastic-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy the Elastic stack
        run: |
          cd tests/ci_test_env
          docker-compose up -d

      # - name: Verify connectivity to Elastic
      #   run: |
      #     curl --verbose --show-error http://localhost:9200

      # - name: Start minikube
      #   uses: medyagh/setup-minikube@master

      - uses: actions/checkout@master
      - uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
      - name: Check Cluster Ready
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
