name: Deploy Environment Action
on: push
jobs:
  elastic-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy the Elastic stack
        run: |
          cd tests/ci_test_env
          docker-compose up -d

      - name: Verify connectivity to Elastic
        run: |
          curl --verbose --show-error http://localhost:9200
