name: Deploy Environment Action
on: push
jobs:
  elastic-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack Elastic stack
        run: |
          cd tests/ci_test_env
          docker-compose up -d
